# Generated by Django 5.2.5 on 2025-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_column='data')),
                ('taken', models.BooleanField(db_column='status', default=False)),
                ('taken_at', models.DateTimeField(blank=True, db_column='horario', null=True)),
            ],
            options={
                'db_table': 'remedios_tomados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome_remedio', max_length=100)),
                ('dosage', models.CharField(db_column='dosagem', max_length=50)),
                ('time', models.TimeField(db_column='horario')),
                ('day', models.CharField(db_column='dia_Semana', max_length=20)),
                ('frequency', models.CharField(db_column='quantidade', max_length=50)),
                ('notes', models.TextField(blank=True, db_column='observacoes', null=True)),
            ],
            options={
                'db_table': 'remedios',
                'managed': False,
            },
        ),
    ]
