# Generated by Django 5.2.5 on 2025-09-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fake_email_migration'),
    ]

    operations = [
    ]
